In [26]:
from scikitplot import annoy

annoy.__version__, dir(annoy), dir(annoy.Annoy)

('2.0.0+git.20251130.8a7e82cb537053926b0ac6ec132b9ccc875af40c',
 ['Annoy',
  'AnnoyIndex',
  'CompressMode',
  'Index',
  'IndexIOMixin',
  'MetaMixin',
  'NDArrayMixin',
  'PickleMixin',
  'PickleMode',
  'PlottingMixin',
  'VectorOpsMixin',
  '__all__',
  '__author__',
  '__author_email__',
  '__builtins__',
  '__cached__',
  '__doc__',
  '__file__',
  '__git_hash__',
  '__loader__',
  '__name__',
  '__package__',
  '__path__',
  '__spec__',
  '__version__',
  '_base',
  '_metadata',
  '_mixins',
  '_utils',
  'annotations',
  'annoylib'],
 ['__class__',
  '__delattr__',
  '__dict__',
  '__dir__',
  '__doc__',
  '__eq__',
  '__format__',
  '__ge__',
  '__getattribute__',
  '__getstate__',
  '__gt__',
  '__hash__',
  '__init__',
  '__init_subclass__',
  '__le__',
  '__len__',
  '__lt__',
  '__ne__',
  '__new__',
  '__reduce__',
  '__reduce_ex__',
  '__repr__',
  '__setattr__',
  '__setstate__',
  '__sizeof__',
  '__sklearn_clone__',
  '__sklearn_is_fitted__',
  '__sklearn_tags__',
  '

In [27]:
import random; random.seed(0)

from scikitplot.annoy import Annoy, AnnoyIndex, Index

AnnoyIndex?

Init signature: AnnoyIndex(self, /, *args, **kwargs)
Docstring:     
Compiled with GCC/Clang. Using AVX instructions.

Approximate Nearest Neighbors index (Annoy) with a small, lazy C-extension wrapper.

::

>>> Annoy(
>>>     f=None,
>>>     metric=None,
>>>     *,
>>>     on_disk_path=None,
>>>     prefault=None,
>>>     schema_version=None,
>>>     seed=None,
>>>     verbose=None,
>>> )

Parameters
----------
f : int or None, optional, default=None
    Vector dimension. If ``0`` or ``None``, dimension may be inferred from the
    first vector passed to ``add_item`` (lazy mode).
    If None, treated as ``0`` (reset to default).
metric : {"angular", "cosine", "euclidean", "l2", "lstsq", "manhattan", "l1", "cityblock", "taxicab", "dot", "@", ".", "dotproduct", "inner", "innerproduct", "hamming"} or None, optional, default=None
    Distance metric (one of 'angular', 'euclidean', 'manhattan', 'dot', 'hamming').
    If omitted and ``f > 0``, defaults to ``'angular'`` (cosine-like).
    If

In [28]:
# =============================================================
# 1. Construction
# =============================================================
idx = Index(f=0, metric="angular")
print("Index dimension:", idx.f)
print("Metric         :", idx.metric)

Index dimension: 0
Metric         : angular


In [29]:
# =============================================================
# 2. Add items
# =============================================================
f=100
n=1000
for i in range(n):
    if(i % (n//10) == 0): print(f"{i} / {n} = {1.0 * i / n}")
    # v = []
    # for z in range(f):
    #     v.append(random.gauss(0, 1))
    v = [random.gauss(0, 1) for _ in range(f)]
    idx.add_item(i, v)

print("Number of items:", idx.get_n_items())
print("Index dimension:", idx.f)
print("Metric         :", idx.metric)
print(idx)

0 / 1000 = 0.0
100 / 1000 = 0.1
200 / 1000 = 0.2
300 / 1000 = 0.3
400 / 1000 = 0.4
500 / 1000 = 0.5
600 / 1000 = 0.6
700 / 1000 = 0.7
800 / 1000 = 0.8
900 / 1000 = 0.9
Number of items: 1000
Index dimension: 100
Metric         : angular
Annoy(**{'f': 100, 'metric': 'angular', 'on_disk_path': None, 'prefault': False, 'schema_version': 0, 'seed': None, 'verbose': None})


In [30]:
# =============================================================
# 3. Build index
# =============================================================
idx.build(10)
print("Trees:", idx.get_n_trees())
print("Memory usage:", idx.memory_usage(), "bytes")
print(idx)
print(idx.info())

Trees: 10
Memory usage: 611056 bytes
Annoy(**{'f': 100, 'metric': 'angular', 'on_disk_path': None, 'prefault': False, 'schema_version': 0, 'seed': None, 'verbose': None})
{'f': 100, 'metric': 'angular', 'on_disk_path': None, 'prefault': False, 'schema_version': 0, 'seed': None, 'verbose': None, 'n_items': 1000, 'n_trees': 10, 'memory_usage_byte': 611056, 'memory_usage_mib': 0.5827484130859375}


In [31]:
idx.query_vectors_by_item(0, 2, include_distances=True, exclude_self=False)[1], \
idx.query_vectors_by_item(0, 2, include_distances=True, exclude_self=True)[1]

(array([0.       , 1.1943145], dtype=float32),
 array([1.1943145, 1.260158 ], dtype=float32))

In [32]:
idx.query_vectors_by_vector(v, 2, include_distances=True, exclude_self=False)[1], \
idx.query_vectors_by_vector(v, 2, include_distances=True, exclude_self=True)[1]

(array([0.       , 1.2334098], dtype=float32),
 array([1.2334098, 1.2354703], dtype=float32))

In [33]:
idx.query_vectors_by_vector(v, 2), idx.query_vectors_by_vector(v, 2), idx.get_item_vector(999) == v

(array([[ 1.85825646e-01, -7.53631964e-02,  5.89749992e-01,
          9.67114806e-01,  1.35593510e+00,  3.09629321e-01,
          4.53732163e-02,  1.63323545e+00, -4.33414221e-01,
          6.56273127e-01, -2.10801029e+00, -6.81089997e-01,
          6.26455247e-01, -1.87813267e-01,  5.35600722e-01,
         -1.49929151e-02, -4.31645304e-01, -2.72294562e-02,
         -7.39129409e-02,  1.06443036e+00, -1.83330035e+00,
         -1.60831845e+00,  8.19162875e-02, -8.22496176e-01,
          3.22450191e-01,  1.23046660e+00,  3.67918983e-02,
         -3.53539139e-02, -1.08923221e+00, -7.82100558e-02,
         -7.20470026e-02, -1.36758363e+00, -2.08533168e-01,
          2.08357978e+00, -8.49443555e-01,  2.85456702e-03,
         -9.54989135e-01, -5.86323619e-01, -6.77605033e-01,
         -1.75384700e+00,  1.55542862e+00, -6.25564933e-01,
          8.22491705e-01, -2.14744210e+00, -1.04479337e+00,
          9.00832653e-01, -8.18001568e-01,  4.79712993e-01,
          2.78624326e-01, -6.13545656e-0

In [34]:
idx.query_vectors_by_vector(v, 1, include_distances=True, exclude_self=False)

(array([[ 7.0559627e-01,  8.3405137e-02, -4.4012317e-01, -2.9675964e-01,
          1.2092408e+00, -2.5936276e-02,  2.2050168e-01,  4.4838023e-01,
         -1.1040581e+00,  2.1362503e+00, -1.5258865e+00, -1.2754282e+00,
          1.3663387e-01, -7.4968874e-02, -1.8051688e-01,  2.7106589e-01,
          7.4674022e-01,  1.3634554e+00,  4.7426748e-01, -6.9738299e-01,
         -3.6311108e-01, -9.7355378e-01,  1.8625422e+00,  6.2557048e-01,
          5.6835204e-01,  1.0293511e-01,  5.5057830e-01, -1.1851449e+00,
         -1.1799835e+00, -3.4091154e-01, -2.0282912e-01,  1.7784323e+00,
          4.0561128e-01,  1.1059277e+00,  9.8452777e-01, -1.6186764e+00,
          7.9445261e-01,  1.4895806e+00,  7.2279853e-01,  7.5155425e-01,
          1.2247714e+00, -4.1345412e-01,  5.3582770e-01, -9.7442977e-03,
          6.5482795e-01, -2.4996635e-01, -5.6917673e-01, -1.2162662e+00,
         -5.2791440e-01, -4.3543351e-01, -5.4880506e-01, -8.1121242e-01,
         -1.4232424e+00,  1.2830684e+00,  2.6763238

In [35]:
idx.kneighbors([v], n_neighbors=1, return_type="vector")

(array([[[ 1.85825646e-01, -7.53631964e-02,  5.89749992e-01,
           9.67114806e-01,  1.35593510e+00,  3.09629321e-01,
           4.53732163e-02,  1.63323545e+00, -4.33414221e-01,
           6.56273127e-01, -2.10801029e+00, -6.81089997e-01,
           6.26455247e-01, -1.87813267e-01,  5.35600722e-01,
          -1.49929151e-02, -4.31645304e-01, -2.72294562e-02,
          -7.39129409e-02,  1.06443036e+00, -1.83330035e+00,
          -1.60831845e+00,  8.19162875e-02, -8.22496176e-01,
           3.22450191e-01,  1.23046660e+00,  3.67918983e-02,
          -3.53539139e-02, -1.08923221e+00, -7.82100558e-02,
          -7.20470026e-02, -1.36758363e+00, -2.08533168e-01,
           2.08357978e+00, -8.49443555e-01,  2.85456702e-03,
          -9.54989135e-01, -5.86323619e-01, -6.77605033e-01,
          -1.75384700e+00,  1.55542862e+00, -6.25564933e-01,
           8.22491705e-01, -2.14744210e+00, -1.04479337e+00,
           9.00832653e-01, -8.18001568e-01,  4.79712993e-01,
           2.78624326e-0

In [37]:
idx.kneighbors([v, v], return_type="id")

(array([[386, 320, 710,  98, 825],
        [386, 320, 710,  98, 825]]),
 array([[1.2334098, 1.2354703, 1.2741706, 1.2761192, 1.2843482],
        [1.2334098, 1.2354703, 1.2741706, 1.2761192, 1.2843482]],
       dtype=float32))

In [38]:
import numpy as np

In [39]:
x = idx.kneighbors_graph([v, v])#.toarray()
np.nonzero(x)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int32),
 array([ 98, 320, 386, 710, 825,  98, 320, 386, 710, 825], dtype=int32))

In [42]:
x = idx.kneighbors_graph([v], mode="distance")#.toarray()
x.toarray()[np.nonzero(x)]

array([1.2761192, 1.2354703, 1.2334098, 1.2741706, 1.2843482],
      dtype=float32)

In [15]:
# by-item (unchanged)
a = idx.query_vectors_by_item(999, 1)

# by-vector now behaves symmetrically
b = idx.query_vectors_by_vector(v, 1)

# if you want explicit control
c = idx.query_vectors_by_vector(v, 1)

# keep self
d = idx.query_vectors_by_vector(v, 1, exclude_self=True)


In [16]:
a ==b, a==c, a==d

(array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]]),
 array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  

In [17]:
b ==a, b==c, b==d

(array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]]),
 array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  

In [18]:
c ==a, c==b, c==d

(array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]]),
 array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  

In [19]:
import numpy as np

# n_neighbors=1
idxs, dists = idx.get_nns_by_vector(v, 1, include_distances=True)
assert isinstance(idxs, list)
assert isinstance(dists, list)
assert len(idxs) == len(dists) == 1

d = np.atleast_1d(np.asarray(dists, float))
w = np.ones_like(d)  # or _get_weights path
assert w.ndim == 1

d,w

(array([0.]), array([1.]))

In [20]:
np.atleast_1d(np.asarray(dists, dtype=float)).tolist()

[0.0]

In [21]:
import random
from scikitplot.utils._time import Timer

n, f = 10_000, 1_000
X = [[random.gauss(0, 1) for _ in range(f)] for _ in range(n)]
q = [[random.gauss(0, 1) for _ in range(f)]]

In [22]:
with Timer("set_params"):
    for m in ["angular", "l1", "l2", ".", "hamming"]:
        idx = Index().set_params(metric=m).fit(X)
        print(m, idx.transform(q))

2025-12-31 14:33:04.944069: I scikitplot 130969828570368 _time.py:45:__enter__] set_params
angular [[7683, 777, 7085, 8364, 3652]]
l1 [[220, 7769, 6729, 7958, 7967]]
l2 [[4333, 4087, 4485, 1977, 6729]]
. [[7292, 7739, 5215, 2826, 8460]]
hamming [[6992, 6034, 5185, 2108, 3386]]
2025-12-31 14:33:07.168344: I scikitplot 130969828570368 _time.py:63:__exit__] Completed in 2.232s


In [23]:
with Timer("rebuild"):
    base = Index(metric="l2").fit(X)

    for m in ["angular", "l1", "l2", "dot", "hamming"]:
        idx_m = base.rebuild(metric=m)          # rebuild-from-index
        print(m, idx_m.transform(q))            # no .fit(X) here

2025-12-31 14:33:07.208904: I scikitplot 130969828570368 _time.py:45:__enter__] rebuild
angular [[7683, 777, 7085, 8364, 3652]]
l1 [[220, 7769, 6729, 7958, 7967]]
l2 [[4333, 4087, 4485, 1977, 6729]]
dot [[7292, 7739, 5215, 2826, 8460]]
hamming [[7496, 4565, 557, 6992, 6034]]
2025-12-31 14:33:08.755323: I scikitplot 130969828570368 _time.py:63:__exit__] Completed in 1.546s


In [1]:
from scikitplot.utils._path import make_path, PathNamer

make_path(root=".", by_day=False, subdir=None, prefix="ANNImputer", ext="annoy")

PosixPath('/work/galleries/examples/00-jupyter_notebooks/annoy/ANNImputer-20260101T053927866Z-000000-080c8bf65f6e411ba877f254149273e0.annoy')

In [2]:
p  =PathNamer(default_prefix="ANNImputer", default_ext="annoy")
p.make_path()

PosixPath('/work/galleries/examples/00-jupyter_notebooks/annoy/scikitplot-artifacts/ANNImputer-20260101T053944192Z-000001-39d364aebd954930aed262c3e7c414b7.annoy')

In [38]:
import os
isinstance(p.make_path(), os.PathLike)

True