In [1]:
from scikitplot import __version__

__version__

'0.5.dev0+git.20251211.a5bef96'

In [2]:
from scikitplot import nc

print(nc.__doc__)


NumCpp: A Templatized Header Only C++ Library with Implementation of the Python NumPy-Compatible API.

* Author: `David Pilger <dpilger26@gmail.com>`_
* License: MIT

Compilers:

* C++ Standards: C++17 C++20 C++23
* MSVC Visual Studio: 2022
* GCC GNU: 13.3, 14.2
* Clang LLVM: 18, 19
* Boost Versions: 1.73+

.. seealso::
   * https://github.com/dpilger26/NumCpp



In [3]:
dir(nc)

['__author__',
 '__author_email__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__git_hash__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_linalg',
 '_version',
 '_wrappers',
 'dot',
 'get_include']

In [4]:
nc.dot?

Signature: nc.dot(a: 'npt.ArrayLike', b: 'npt.ArrayLike') -> 'np.ndarray'
Docstring:
dot(a: numpy.ndarray, b: numpy.ndarray) -> numpy.ndarray


dot(a, b)

Dot product of two arrays using the C++ NumCpp backend.

This function behaves similarly to :func:`numpy.dot` for 1-D and 2-D
arrays but executes the computation in C++ via the NumCpp library.

Parameters
----------
a, b : array_like
    Input vectors or matrices. They are converted to
    :class:`numpy.ndarray` without copying whenever possible.
    Arrays must

    * have the same dtype, and
    * be 1-D or 2-D.

    For 1-D inputs, the result is a scalar 0-D array.
    For 2-D inputs, standard matrix multiplication rules apply.

Returns
-------
out : numpy.ndarray
    Dot product of `a` and `b`. The result dtype matches the input
    dtype for the supported dtypes.

Raises
------
ValueError
    If either input has more than 2 dimensions.
TypeError
    If the dtypes of `a` and `b` do not match, or if the dtype is
    not supported.

In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]).astype('uint8')
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [6]:
nc.dot(a, b)

array([[19, 22],
       [43, 50]])

In [14]:
a = [[1,2,True,1]]
b = [[5,6,7,8]]
nc.dot(a, b)

array([[32]])